menu:
  技术: /archives
  阅读: /reading
  关于: /about

archive_date_format: MMM DD
excerpt_link: 阅读全文

widgets:
  - blogroll
  - tagcloud
  - category

blogrolls:
  - 原CSDN博客地址: http://blog.csdn.net/shanno
  - 原CNBLOG博客地址: http://www.cnblogs.com/shanno 

search: false

fancybox: true

duoshuo_shortname: shannon

