menu:
  Home: /
  Archives: /archives
  About: /about

archive_date_format: MMM DD
excerpt_link: 阅读全文

widgets:
  - blogroll
  - tagcloud
  - category

blogrolls:
  - 原博客地址: http://www.cnblogs.com/shanno 

search: false

fancybox: true

duoshuo_shortname: shannon

