menu:
  技术: /archives
  阅读: /reading
  关于: /about

excerpt_link: Read More
archive_date_format: MMM DD

widgets:
 - blogroll
 - tagcloud
 - category
# - category
#  - tag
#  - tagcloud
#  - blogroll
#  - recent_comments

blogrolls:
  - 酷壳: http://coolshell.cn
  - 原CSDN博客地址: http://blog.csdn.net/shanno
  - 原CNBLOG博客地址: http://www.cnblogs.com/shanno

fancybox: true
duoshuo_shortname: shannon

#google_analytics:
baidu_analytics: true 

favicon: /favicon.ico
